import type { Metadata } from "next";
import localFont from "next/font/local";
import {DM_Sans} from "next/font/google"
import "./globals.css";


export const dm_sans_init = DM_Sans(
  {
    subsets: ['latin'],
    display:'swap',
    variable:'--font-dm-sans',
    weight: "300"
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans_init.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
